const { verifyAnonAadhaarProof } = require("@anon-aadhaar/core");

/**
 * Verifies a ZK proof cryptographically
 * @param {Object} proof The ZKP generated by frontend
 * @param {Array} publicSignals Publicly revealed safe data (e.g., isAbove18, isVerified)
 * @returns {Promise<boolean>}
 */
async function verifyProof(proof, publicSignals) {
  try {
    console.log("Checking REAL cryptographic proof...", {
      hasProof: !!proof,
      publicSignals
    });

    // Uses the official Anon Aadhaar SDK to perform cryptographic ZKP verification
    const isValid = await verifyAnonAadhaarProof({
      proof,
      publicSignals,
    });

    return isValid;
  } catch (err) {
    console.error("ZK verification failed:", err);
    return false;
  }
}

module.exports = verifyProof;
